# This playbook will install MSMTP on the system
---
- name: install MSMTP
  hosts: all
  become: yes 

  tasks:
  
  - name: Install MSMTP
    ansible.builtin.package:
      name: msmtp
      state: present 

  - name: Create MSMTP configuration file
    ansible.builtin.copy:
      content: |
        # Set default values for all following accounts.
        defaults
        auth           on
        tls            on
        tls_trust_file /etc/ssl/certs/ca-certificates.crt
        logfile        /var/log/msmtp.log

        # My Mail
        account        hero-elzinga
        host           mail.hero-elzinga.net
        port           587
        from           {{ hostvars[inventory_hostname]['ansible_hostname'] }}@enterprise.org
        user           UU@hero-elzinga.net
        password       R2!SKH4$G2C6&Mn4

        # Set a default account
        # This needs to be at the end!
        account default: hero-elzinga
      dest: /etc/msmtprc
      mode: '0600'

  - name: Create link to MSMTP executable in /usr/sbin/sendmail
    ansible.builtin.file:
      src: /usr/bin/msmtp
      dest: /usr/sbin/sendmail
      state: link

  - name: Ensure MSMTP log file exists and has correct permissions
    ansible.builtin.file:
      path: /var/log/msmtp.log
      state: touch
      mode:  0655
      owner: root
      group: root
      
  - name: Send test email using MSMTP
    ansible.builtin.command:
       cmd: echo -e "Subject: Testmail\n\nMSMTP has sucessfully been installed on {{ hostvars[inventory_hostname]['ansible_hostname'] }}" | sendmail -v root@hero-elzinga.net